# Generated by Django 5.2 on 2025-05-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
