# Generated by Django 5.2 on 2025-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name=100)),
                ('description', models.TextField(verbose_name=100)),
                ('is_completed', models.BooleanField()),
            ],
        ),
    ]
